moviepro/movieapp/urls.py
from . import views
from django.urls import path

app_name = 'movieapp'

urlpatterns = [

    path('', views.index,name='index'),
    path('sports/', views.sports,name='sports'),
    path('detail/<int:movie_id>/', views.detail, name='detail'),
    path('sport_detail/<int:sport_id>/', views.sport_detail, name='sport_detail'),
    path('add/', views.add_movie, name= 'add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),

]












#
# from django.contrib import admin
# from django.urls import include, path
#
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('movieapp/', include('movieapp.urls', namespace='movieapp')),
#     # other paths...
# ]

moviepro/moviepro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls')),
    path('search/', include('search.urls')),
    path('wishlist/', include('wishlist.urls')),

]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

moviepro/search/urls.py
from . import views
from django.urls import path

app_name = 'search'

urlpatterns = [

    path('', views.search_result, name='search_result')

]

moviepro/wishlist/urls.py
from . import views
from django.urls import path

app_name = 'wishlist'

urlpatterns = [
    path('add/<int:film_id>/', views.add_list, name='add_list'),
    path('', views.movies_detail, name='movies_detail'),
    path('delete/<int:film_id>/' ,views.delete,name='delete'),

]

moviepro/movieapp/models.py
from django.db import models

# Create your models here.

class Movies( models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

class Sports( models.Model):
    name = models.CharField(max_length=255)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery1')

    def __str__(self):
        return self.name

moviepro/search/models.py
from django.db import models

# Create your models here.

moviepro/wishlist/models.py
from django.db import models
from movieapp.models import Movies
# Create your models here.


class Movie(models.Model):
    cinema_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)


    class Meta:
        db_table = 'Movie'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cinema_id)

class Movieitem(models.Model):
    movie = models.ForeignKey(Movies,on_delete=models.CASCADE)
    film = models.ForeignKey(Movie,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'Movieitem'

    def __str__(self):
        return '{}'.format(self.movie)

moviepro/movieapp/forms.py
from django import forms
from . models import Movies


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movies
        fields = ['name', 'description', 'year', 'img']

moviepro/movieapp/views.py
from django.shortcuts import render, redirect
from . models import Movies,Sports
from . forms import MovieForm

# Create your views here.

def index(request):
    movies = Movies.objects.all()
    context = {
        'movie_list': movies
    }
    return render(request, 'index.html', context)

def sports(request):
    sports = Sports.objects.all()
    film1 = {
        'sports_list': sports
    }
    return render(request, 'sports.html', film1)

def sport_detail(request,sport_id):
    sport=Sports.objects.get(id=sport_id)
    return render(request, 'sport_detail.html',{'sport': sport})

def detail(request,movie_id):
    movie=Movies.objects.get(id=movie_id)
    return render(request, 'detail.html',{'movie': movie})


def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        description = request.POST.get('description')
        year = request.POST.get('year')
        img = request.FILES.get('img')
        movie = Movies(name=name, description=description, year=year,img=img)
        movie.save()
    return render(request, 'add.html')
def update(request,id):
    movie = Movies.objects.get(id=id)
    form = MovieForm(request.POST or None,request.FILES,instance=movie)

    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form, 'movie':movie})
def delete(request,id):
    if request.method == 'POST':
        movie=Movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

moviepro/search/views.py
from django.shortcuts import render
from movieapp.models import Movies,Sports

from django.db.models import Q

def search_result(request):
    movie = None
    query = None

    if 'q' in request.GET:
        query = request.GET.get('q')
        movie = Movies.objects.all().filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'search.html', {'query': query, 'movie': movie})

moviepro/wishlist/views.py
from movieapp.models import Movies
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from .models import Movie, Movieitem

def _movie_id(request):
    film = request.session.session_key
    if not film:
        film = request.session.create()
    return film

def add_list(request, film_id):
    movie = Movies.objects.get(id=film_id)

    try:
        film = Movie.objects.get(cinema_id=_movie_id(request))
    except Movie.DoesNotExist:
        film = Movie.objects.create(
            cinema_id=_movie_id(request)
        )
        film.save()
    try:
        movie_item = Movieitem.objects.get(movie=movie, film=film)

    except Movieitem.DoesNotExist:
        movie_item = Movieitem.objects.create(
            movie=movie,
            quantity=1,
            film=film
        )
        movie_item.save()

    return redirect('wishlist:movies_detail')

def movies_detail(request, movie_items=None):
    try:
        film = Movie.objects.get(cinema_id=_movie_id(request))
        movie_items = Movieitem.objects.filter(film=film, active=True)
    except ObjectDoesNotExist:
        pass

    return render(request, 'wishlist.html', {'movie_items': movie_items})

def delete(request, film_id):
    film = Movie.objects.get(cinema_id=_movie_id(request))
    movie =  get_object_or_404(Movies,id=film_id)
    movie_item = Movieitem.objects.get(movie=movie,film=film)
    movie_item.delete()

    return redirect('wishlist:movies_detail')

moviepro/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="name">
    <input type="text" name="description" placeholder="description">
    <input type="text" name="year" placeholder="year">
    <input type="file" name="img">
    <input type="submit">
</form>
{% endblock %}
</body>
</html>

moviepro/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>welcome</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body style="background-color:#000000;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-black">
      <a class="navbar-brand" href="{% url 'movieapp:index' %}" style="color: white;"><h3 style="color:yellow;">CinemaWorld</h3></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'movieapp:index' %}" style="color: white;">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movieapp:sports'  %}" style="color: white;">Sports</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#" style="color: white;">New</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#" style="color: white;">Lists</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white;">
              Guide
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#" style="color: black;">Connect your TV</a>
              <a class="dropdown-item" href="#" style="color: black;">Apps</a>
              <a class="dropdown-item" href="#" style="color: black;">About Us</a>
              <a class="dropdown-item" href="#" style="color: black;">Just watch media</a>
              <a class="dropdown-item" href="#" style="color: black;">Terms and use</a>
              <a class="dropdown-item" href="#" style="color: black;">Privacy & Policy</a>
            </div>
          </li>
        </ul>
        <div class="main">
           <div class="input-group">
              <form class="d-flex" action="{% url 'search:search_result' %}" method="get">
                 {% csrf_token %}
                 <input type="text" class="form-control" placeholder="Search movies" aria-label="Search" name="q">&nbsp;&nbsp;
                 <div class="input-group-append">
                    <button class="btn btn-secondary" type="submit" style="background-color: #f26522; border-color:#f26522 ">
                       Search
                    </button>
                 </div>
              </form>
           </div>
        </div>
      </div>
    </nav>

{% block body %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

moviepro/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
    input[type=submit] {
      background-color: #02B81D;
      border-radius:20px;
      color: white;
      padding: 12px 28px;
      text-decoration: none;
      margin: 4px 2px;
      cursor: pointer;
      text-align: center;
      justify-content: center;

    }
    .alert {
      padding: 40px;
      background-color: #FB3A1F;
      color: white;
      width: 93%;
      text-align: center;
      justify-content: center;
    }
    .btn {
      color: white;
      padding: 12px 28px;
      cursor: pointer;
      border-radius:20px;
    }
    .warning {background-color:#FAC840;}
    .warning:hover {background: #e68a00;}

</style>
</head>
<body>

<form method="POST">
    {% csrf_token %}
    <h2 style="text-align: center">Alert !</h2>
    <div class="alert">
      <strong>Danger!</strong>  are you sure to delete   ?&nbsp;<input type="submit" value="delete"><input class="btn btn-warning" type="submit" value="Cancel">
    </div>
</form>

</body>
</html>

moviepro/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6"><br><br><br><br>
            <img src="{{movie.img.url}}" style="width: 280px; height:390px;"><br>
        </div>
        <div class="col-md-6" style="color:white;"><br><br><br><br><br><br>
            <h1>{{movie.name}}</h1><br>
            <h3>({{movie.year}})</h3><br>
            <strong>{{movie.description}}</strong><br>
            <br>
            <a class="btn btn-secondary" href="{% url 'wishlist:add_list' movie.id %}">Watch later</a>
<!--            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>&nbsp;&nbsp;&nbsp;-->
<!--            <a class ="btn btn-danger" href="{%url 'movieapp:delete' movie.id %}">Delete</a>-->
        </div>
    </div>
</div>
{% endblock %}

moviepro/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
    input[type=submit] {
      background-color: #04AA6D;
      border: none;
      color: white;
      padding: 16px 32px;
      text-decoration: none;
      margin: 4px 2px;
      cursor: pointer;
      border-radius:20px
}
</style>
</head>
<body>
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

</body>
</html>

moviepro/templates/index.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>welcome</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th>
                        <h1 style="color:#E7CCCC;">Stream movies online</h1>
                        <br>
                        <p style="color:#FFFFFF;" >Need some help deciding what to watch before all your popcorn runs out? We’ve got you covered! With this guide you can find the best movies to watch online across all languages, eras, and genres all under one roof. From seeing where to watch movies for free to keeping track of all the new movie releases, our easy-to-use guide is your go-to hub for all things movies.</p>
                    </th>
                </tr>
            </thead>
        </table>
    </div>
    <div class="container">
        <br>
        <div class="row">
            {% for i in movie_list %}
            <div class="col-lg-3 col-sm-4">
                <div class="box_main">
                    <h5>.</h5>
                    <a href="{% url 'movieapp:detail' i.id %}"><img class="card-img-top my_image" src="{{i.img.url}}" alt="" style="width: 270px; height:390px;"></a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <br>
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th>
                        <a href="#"><h4 style="color:#E7CCCC;">Cinemaworld is available in</h4></a>

                    </th>
                </tr>
            </thead>
        </table>
    </div>
    <div class="container">
        <div class="row" style="color:white;">
            <ul>
               <h5>North America</h5>
               <li><a href="#">Bermuda</a></li><br>
               <li><a href="#">Mexico</a></li><br>
               <li><a href="#">Canada</a></li><br>
               <li><a href="#">United States</a></li><br>
               <li><a href="#">Australia</a></li><br>
            </ul>
             <ul>
               <h5>South America</h5>
               <li><a href="#">Bolivia</a></li><br>
               <li><a href="#">Argentina</a></li><br>
               <li><a href="#">Brazil</a></li><br>
               <li><a href="#">Paraguay</a></li><br>
               <li><a href="#">Guyana</a></li><br>
            </ul>
            <ul>
               <h5>Europe</h5>
               <li><a href="#">Albania</a></li><br>
               <li><a href="#">Androrra</a></li><br>
               <li><a href="#">Azerbaijan</a></li><br>
               <li><a href="#">Belarus</a></li><br>
               <li><a href="#">Austria</a></li><br>
            </ul>
            <ul>
               <h5>Asia</h5>
               <li><a href="#">Hong Kong</a></li><br>
               <li><a href="#">India</a></li><br>
               <li><a href="#">Indonesia</a></li><br>
               <li><a href="#">Lebanon</a></li><br>
               <li><a href="#">Japan</a></li><br>
            </ul>
            <ul>
               <h5>Africa</h5>
               <li><a href="#">Algeria</a></li><br>
               <li><a href="#">Angola</a></li><br>
               <li><a href="#">Cameroon</a></li><br>
               <li><a href="#">Burkina Faso</a></li><br>
               <li><a href="#">Canada</a></li><br>
            </ul>

            <ul>
               <h5>Central America</h5>
               <li><a href="#">Guatemala</a></li><br>
               <li><a href="#">El Salvador</a></li><br>
               <li><a href="#">Costa Rica</a></li><br>
               <li><a href="#">Honduras</a></li><br>
               <li><a href="#">Nicaragua</a></li><br>
            </ul>
            <ul>
               <h5>London</h5>
               <li><a href="#">Albania</a></li><br>
                <li><a href="#">Belarus</a></li><br>
               <li><a href="#">Androrra</a></li><br>
               <li><a href="#">Azerbaijan</a></li><br>
               <li><a href="#">Austria</a></li><br>
            </ul>
            <ul>
               <h5>spanish</h5>
               <li><a href="#">Albania</a></li><br>
               <li><a href="#">Androrra</a></li><br>
               <li><a href="#">Azerbaijan</a></li><br>
               <li><a href="#">Belarus</a></li><br>
               <li><a href="#">Austria</a></li><br>
            </ul>
        </div>
    </div>

    <div style="text-align:center; color:white;">
         <div class="container">
            <p class="copyright_text">© 2024 All Rights Reserved.<a href="#"></a></p>
         </div>
    </div>
</body>
</html>
{% endblock %}

moviepro/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>search</title>
</head>
<body>
{% block body %}

    <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-center">
        <table class="table my_custom_table">
            <h4  style="color:#FFFFFF;">  results for :<b>   "{{query}}"</b></h4>
        </table>
    </div>
    <div class="container">
        <div class="row mx-auto">
            {% for i in movie %}
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th>
                                <div class="row">
                                    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                                        <div style="min-width: 18rem;">
                                            <img src="{{ i.img.url }}" style="width: 300px;" alt="{{ i.name }}">
                                        </div>
                                    </div>
                                    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                                        <div style="color:#FFFFFF;">
                                            <h1 class="my_prod_title">{{ i.name }}</h1>
                                            <p><h3>Year ({{ i.year }})</h3></p>
                                            <p class="text-justify my_prod_text"><h4>{{ i.description }}</h4></p>
                                            <br>
                                        </div>
                                    </div>
                                </div>
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>
            {% empty %}
                <div class="row mx-auto">
                    <p class="text-center my_search_text"><h3 style="color:#FF2300;"> You have searched for :<b>  "{{query}}"  </b>There is no product that matches the search criteria.</h3></p>
                </div>
            {% endfor %}
        </div>
    </div>



{% endblock %}
</body>
</html>

moviepro/templates/sport_detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6"><br><br><br><br>
            <img src="{{sport.img.url}}" style="width: 280px; height:390px;"><br>
        </div>
        <div class="col-md-6" style="color:white;"><br><br><br><br><br><br>
            <h1>Name  - {{sport.name}}</h1><br>
            <h3>Year  - ({{sport.year}})</h3><br>
            <strong>{{sport.desc}}</strong><br>
            <br>
        </div>
    </div>
</div>
{% endblock %}

moviepro/templates/sports.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>sports</title>
</head>
<body>
{% block body %}
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th>
                        <h1 style="color:#E7CCCC;">Stream movies online</h1>
                        <br>
                        <p style="color:#FFFFFF;" >cinemaworld is using its strength in storytelling to create a deep catalog of docu-series about various sports and athletes.</p>
                    </th>
                </tr>
            </thead>
        </table>
    </div>
    <div class="container">
        <br>
        <div class="row">
            {% for sport in sports_list %}
            <div class="col-lg-3 col-sm-4">
                <div class="box_main">
                    <h5>.</h5>
                    <a href="{% url 'movieapp:sport_detail' sport.id %}"><img class="card-img-top my_image" src="{{sport.img.url}}" alt="" style="width: 270px; height:390px;"></a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <br>
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th>
                        <a href="#"><h4 style="color:#E7CCCC;">Cinemaworld is available in</h4></a>

                    </th>
                </tr>
            </thead>
        </table>
    </div>
    <div class="container">
        <div class="row" style="color:white;">
            <ul>
               <h5>North America</h5>
               <li><a href="#">Bermuda</a></li><br>
               <li><a href="#">Mexico</a></li><br>
               <li><a href="#">Canada</a></li><br>
               <li><a href="#">United States</a></li><br>
               <li><a href="#">Australia</a></li><br>
            </ul>
             <ul>
               <h5>South America</h5>
               <li><a href="#">Bolivia</a></li><br>
               <li><a href="#">Argentina</a></li><br>
               <li><a href="#">Brazil</a></li><br>
               <li><a href="#">Paraguay</a></li><br>
               <li><a href="#">Guyana</a></li><br>
            </ul>
            <ul>
               <h5>Europe</h5>
               <li><a href="#">Albania</a></li><br>
               <li><a href="#">Androrra</a></li><br>
               <li><a href="#">Azerbaijan</a></li><br>
               <li><a href="#">Belarus</a></li><br>
               <li><a href="#">Austria</a></li><br>
            </ul>
            <ul>
               <h5>Asia</h5>
               <li><a href="#">Hong Kong</a></li><br>
               <li><a href="#">India</a></li><br>
               <li><a href="#">Indonesia</a></li><br>
               <li><a href="#">Lebanon</a></li><br>
               <li><a href="#">Japan</a></li><br>
            </ul>
            <ul>
               <h5>Africa</h5>
               <li><a href="#">Algeria</a></li><br>
               <li><a href="#">Angola</a></li><br>
               <li><a href="#">Cameroon</a></li><br>
               <li><a href="#">Burkina Faso</a></li><br>
               <li><a href="#">Canada</a></li><br>
            </ul>

            <ul>
               <h5>Central America</h5>
               <li><a href="#">Guatemala</a></li><br>
               <li><a href="#">El Salvador</a></li><br>
               <li><a href="#">Costa Rica</a></li><br>
               <li><a href="#">Honduras</a></li><br>
               <li><a href="#">Nicaragua</a></li><br>
            </ul>
            <ul>
               <h5>London</h5>
               <li><a href="#">Albania</a></li><br>
                <li><a href="#">Belarus</a></li><br>
               <li><a href="#">Androrra</a></li><br>
               <li><a href="#">Azerbaijan</a></li><br>
               <li><a href="#">Austria</a></li><br>
            </ul>
            <ul>
               <h5>spanish</h5>
               <li><a href="#">Albania</a></li><br>
               <li><a href="#">Androrra</a></li><br>
               <li><a href="#">Azerbaijan</a></li><br>
               <li><a href="#">Belarus</a></li><br>
               <li><a href="#">Austria</a></li><br>
            </ul>
        </div>
    </div>

    <div style="text-align:center; color:white;">
         <div class="container">
            <p class="copyright_text">© 2024 All Rights Reserved.<a href="#"></a></p>
         </div>
    </div>
{% endblock %}
</body>
</html>

moviepro/templates/wishlist.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>movie_lists</title>
</head>
<body>
{% block body %}
    <div>
        <div class="text-center">
            <br><br>
            <h1 class="text-center my_title">
                {% if movie_items %}
                <br>
                    <h1 style="color:#D6C8C6;"><b>Library</b></h1>
                {% else %}
                <br>
                <h3 style="color:#FA3516;">Empty list</h3>
                {% endif %}
            </h1>
            <br>
            {% if not movie_items %}
                <p class="text-center">
                    <h5 style="color:#9B8581;">watch new releases <a href="{% url 'movieapp:index' %}"><br><br><button type="button" class="btn btn-outline-success">continue</button></a></h5>
                </p>
            {% endif %}
        </div>
    </div>

    {% if movie_items %}
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                    <tr>
                        <th colspan="5">
                            <h3 style="color:#9B8581;">Saved movies</h3>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for movie in movie_items %}
                    <tr>
                        <td>
                            <img src="{{ movie.movie.img.url }}" style="width: 280px; height: 390px;"><br>
                        </td>
                        <td class="text-left">
                            <br><br>
                            <h3 style="color:#D6C8C6;">{{ movie.movie.name }}</h3><br>
                            <h5 style="color:#D6C8C6;">{{ movie.movie.description }}</h5><br><br><br>
                            <a href="{% url 'wishlist:delete' movie.movie.id %}"><button type="button" class="btn btn-outline-danger">Delete</button></a>
                            &nbsp;&nbsp;&nbsp;

                            <button type="button" class="btn btn-outline-success" onclick="alert('downloading started plaese wait !')">Download</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
{% endblock %}
</body>
</html>